import sqlite3
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "database" / "app.db"


def get_connection() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cursor.execute(
     """
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            codigo TEXT NOT NULL UNIQUE,
            nome TEXT NOT NULL,
            descricao TEXT DEFAULT '',
            qtd_estoque INTEGER NOT NULL DEFAULT 0,
            qtd_minima INTEGER NOT NULL DEFAULT 0,
            preco REAL NOT NULL DEFAULT 0,
            custo REAL NOT NULL DEFAULT 0,
            fornecedor TEXT DEFAULT '',
            garantia TEXT DEFAULT '',
            validade TEXT DEFAULT '',
            lote TEXT DEFAULT '',
            status TEXT NOT NULL DEFAULT 'Disponível',
            tipo_produto TEXT DEFAULT '',
            imagem TEXT DEFAULT '',
            imagem_hover TEXT DEFAULT '',
            cor TEXT DEFAULT '',
            tamanhos TEXT DEFAULT '',
            ativo INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS stock_movements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            codigo_produto TEXT NOT NULL,
            nome_produto TEXT NOT NULL,
            tipo TEXT NOT NULL,
            quantidade INTEGER NOT NULL,
            origem TEXT NOT NULL,
            observacao TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    conn.commit()
    conn.close()


def seed_products() -> None:
    conn = get_connection()
    cursor = conn.cursor()

    existing = cursor.execute("SELECT COUNT(*) AS total FROM products").fetchone()
    if existing["total"] > 0:
        conn.close()
        return

    products = [
    {
        "codigo": "ECO-001",
        "nome": "Ecobag Frankenstein",
        "descricao": "Ecobag temática Frankenstein",
        "qtd_estoque": 20,
        "qtd_minima": 5,
        "preco": 59.90,
        "custo": 25.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-ECO-2026-01",
        "status": "Disponível",
        "tipo_produto": "Ecobag",
        "imagem": "img/ecobag-frankenstein-a.png",
        "imagem_hover": "img/ecobag-frankenstein-b.png",
        "cor": "branco",
        "tamanhos": "",
    },
    {
        "codigo": "NEC-002",
        "nome": "Necessaire Monstros",
        "descricao": "Necessaire temática monstros clássicos",
        "qtd_estoque": 15,
        "qtd_minima": 4,
        "preco": 29.90,
        "custo": 12.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-NEC-2026-01",
        "status": "Disponível",
        "tipo_produto": "Acessório",
        "imagem": "img/necessaire-a.png",
        "imagem_hover": "img/necessaire-b.png",
        "cor": "branco",
        "tamanhos": "",
    },
    {
        "codigo": "CAM-003",
        "nome": "Camisa O agente secreto off white",
        "descricao": "Camiseta temática O Agente Secreto",
        "qtd_estoque": 18,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 40.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-01",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/agente-a.png",
        "imagem_hover": "img/agente-b.png",
        "cor": "branco",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "CAM-004",
        "nome": "Camisa Evil Dead olhos",
        "descricao": "Camiseta temática Evil Dead",
        "qtd_estoque": 18,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 40.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-02",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/evil-a.png",
        "imagem_hover": "img/evil-b.png",
        "cor": "branco",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "CAM-005",
        "nome": "Camisa Halloween",
        "descricao": "Camiseta temática Halloween",
        "qtd_estoque": 18,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 40.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-03",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/halloween-a.png",
        "imagem_hover": "img/halloween-b.png",
        "cor": "preto",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "CAM-006",
        "nome": "Camisa Jaws - Tubarão",
        "descricao": "Camiseta filme Tubarão",
        "qtd_estoque": 18,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 40.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-04",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/jaws-a.png",
        "imagem_hover": "img/jaws-b.png",
        "cor": "preto",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "CAM-007",
        "nome": "Camisa Monstros",
        "descricao": "Camiseta temática monstros",
        "qtd_estoque": 18,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 40.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-05",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/monstros-a.png",
        "imagem_hover": "img/monstros-b.png",
        "cor": "preto",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "CAM-008",
        "nome": "Camisas com estampa personalizada",
        "descricao": "Camiseta personalizada",
        "qtd_estoque": 25,
        "qtd_minima": 5,
        "preco": 85.41,
        "custo": 35.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-CAM-2026-06",
        "status": "Disponível",
        "tipo_produto": "Camiseta",
        "imagem": "img/custom-a.png",
        "imagem_hover": "img/custom-b.png",
        "cor": "preto",
        "tamanhos": "2P,P,M,G,2G,3G,4G",
    },
    {
        "codigo": "MOC-009",
        "nome": "Mochila com fecho personalizada",
        "descricao": "Mochila personalizada com fecho",
        "qtd_estoque": 10,
        "qtd_minima": 3,
        "preco": 59.90,
        "custo": 25.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-MOC-2026-01",
        "status": "Disponível",
        "tipo_produto": "Mochila",
        "imagem": "img/mochila-fecho-a.png",
        "imagem_hover": "img/mochila-fecho-b.png",
        "cor": "preto",
        "tamanhos": "",
    },
    {
        "codigo": "MOC-010",
        "nome": "Mochila saco personalizada",
        "descricao": "Mochila saco personalizada",
        "qtd_estoque": 10,
        "qtd_minima": 3,
        "preco": 49.90,
        "custo": 20.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-MOC-2026-02",
        "status": "Disponível",
        "tipo_produto": "Mochila",
        "imagem": "img/mochila-saco-a.png",
        "imagem_hover": "img/mochila-saco-b.png",
        "cor": "preto",
        "tamanhos": "",
    },
    {
        "codigo": "ECO-011",
        "nome": "Ecobags - personalizada",
        "descricao": "Ecobag personalizada",
        "qtd_estoque": 14,
        "qtd_minima": 4,
        "preco": 59.90,
        "custo": 25.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-ECO-2026-02",
        "status": "Disponível",
        "tipo_produto": "Ecobag",
        "imagem": "img/ecobag-personalizada-a.png",
        "imagem_hover": "img/ecobag-personalizada-b.png",
        "cor": "branco",
        "tamanhos": "",
    },
    {
        "codigo": "ACT-012",
        "nome": "Action figure do Rambo",
        "descricao": "Boneco colecionável Rambo",
        "qtd_estoque": 6,
        "qtd_minima": 2,
        "preco": 265.91,
        "custo": 120.00,
        "fornecedor": "Colecionáveis",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-ACT-2026-01",
        "status": "Disponível",
        "tipo_produto": "Action Figure",
        "imagem": "img/rambo-a.png",
        "imagem_hover": "img/rambo-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "ACT-013",
        "nome": "Action figure - O profissional filme.",
        "descricao": "Boneco do filme O Profissional",
        "qtd_estoque": 6,
        "qtd_minima": 2,
        "preco": 190.00,
        "custo": 90.00,
        "fornecedor": "Colecionáveis",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-ACT-2026-02",
        "status": "Disponível",
        "tipo_produto": "Action Figure",
        "imagem": "img/leon-a.png",
        "imagem_hover": "img/leon-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "GAR-014",
        "nome": "Garrafa de alumínio do Toy Story edição de 30 anos",
        "descricao": "Garrafa de alumínio Toy Story",
        "qtd_estoque": 12,
        "qtd_minima": 4,
        "preco": 49.90,
        "custo": 20.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-GAR-2026-01",
        "status": "Disponível",
        "tipo_produto": "Garrafa",
        "imagem": "img/toy-a.png",
        "imagem_hover": "img/toy-b.png",
        "cor": "azul",
        "tamanhos": "",
    },
    {
        "codigo": "MAS-015",
        "nome": "Máscara Darth Vader",
        "descricao": "Máscara colecionável Darth Vader",
        "qtd_estoque": 5,
        "qtd_minima": 2,
        "preco": 227.91,
        "custo": 110.00,
        "fornecedor": "Colecionáveis",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-MAS-2026-01",
        "status": "Disponível",
        "tipo_produto": "Máscara",
        "imagem": "img/darth-a.png",
        "imagem_hover": "img/darth-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "BOX-016",
        "nome": "Box Cinema Policia Hong Kong DVD",
        "descricao": "Box de filmes Cinema Polícia Hong Kong",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 94.05,
        "custo": 40.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-BOX-2026-01",
        "status": "Disponível",
        "tipo_produto": "Box DVD",
        "imagem": "img/hongkong-a.png",
        "imagem_hover": "img/hongkong-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "BOX-017",
        "nome": "Box - Cinema Yakuza 5 DVD",
        "descricao": "Box Cinema Yakuza 5 em DVD",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 94.05,
        "custo": 40.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-BOX-2026-02",
        "status": "Disponível",
        "tipo_produto": "Box DVD",
        "imagem": "img/yakuza-a.png",
        "imagem_hover": "img/yakuza-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "BOX-018",
        "nome": "Box - Os irmãos Marx filme",
        "descricao": "Box do filme Os Irmãos Marx",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 94.05,
        "custo": 40.00,
        "fornecedor": "Loja Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-BOX-2026-03",
        "status": "Disponível",
        "tipo_produto": "Box DVD",
        "imagem": "img/marx-a.png",
        "imagem_hover": "img/marx-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "LIV-019",
        "nome": "Livro - BTK",
        "descricao": "Livro sobre o caso BTK",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 64.99,
        "custo": 25.00,
        "fornecedor": "Editora",
        "garantia": "Sem garantia",
        "validade": "Não se aplica",
        "lote": "L-LIV-2026-01",
        "status": "Disponível",
        "tipo_produto": "Livro",
        "imagem": "img/btk-a.png",
        "imagem_hover": "img/btk-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "LIV-020",
        "nome": "Livro O segredo dos corpos",
        "descricao": "Livro investigativo",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 49.99,
        "custo": 20.00,
        "fornecedor": "Editora",
        "garantia": "Sem garantia",
        "validade": "Não se aplica",
        "lote": "L-LIV-2026-02",
        "status": "Disponível",
        "tipo_produto": "Livro",
        "imagem": "img/corpos-a.png",
        "imagem_hover": "img/corpos-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "LIV-021",
        "nome": "Livro Menina Má",
        "descricao": "Livro suspense",
        "qtd_estoque": 8,
        "qtd_minima": 3,
        "preco": 44.99,
        "custo": 18.00,
        "fornecedor": "Editora",
        "garantia": "Sem garantia",
        "validade": "Não se aplica",
        "lote": "L-LIV-2026-03",
        "status": "Disponível",
        "tipo_produto": "Livro",
        "imagem": "img/menina-a.png",
        "imagem_hover": "img/menina-b.png",
        "cor": "",
        "tamanhos": "",
    },
    {
        "codigo": "GAR-022",
        "nome": "Garrafa de alumínio do Quarteto Fantástico",
        "descricao": "Garrafa temática Quarteto Fantástico",
        "qtd_estoque": 12,
        "qtd_minima": 4,
        "preco": 79.90,
        "custo": 30.00,
        "fornecedor": "Fornecedor Geek",
        "garantia": "90 dias",
        "validade": "Não se aplica",
        "lote": "L-GAR-2026-02",
        "status": "Disponível",
        "tipo_produto": "Garrafa",
        "imagem": "img/quarteto-a.png",
        "imagem_hover": "img/quarteto-b.png",
        "cor": "azul",
        "tamanhos": "",
    },
]

    cursor.executemany(
    """
    INSERT INTO products (
        codigo, nome, descricao, qtd_estoque, qtd_minima, preco, custo,
        fornecedor, garantia, validade, lote, status, tipo_produto,
        imagem, imagem_hover, cor, tamanhos, ativo
    )
    VALUES (
        :codigo, :nome, :descricao, :qtd_estoque, :qtd_minima, :preco, :custo,
        :fornecedor, :garantia, :validade, :lote, :status, :tipo_produto,
        :imagem, :imagem_hover, :cor, :tamanhos, 1
    )
    """,
    products,
)

    conn.commit()
    conn.close()